project setup
Talentica/cabAd pull request #1
Opened 2020-02-10 06:12 UTC by supritaj

2020-02-10 13:57 UTC, mohitsorde requested changes
Now since we have folders remove the corresponding models.py, views.py, tests.py files ... Add a views folder as well

2020-02-10 13:57 UTC, mohitsorde commented on cabAd/settings.py
> +INSTALLED_APPS = [
Register the app

2020-02-10 14:00 UTC, mohitsorde commented
Also add a middlewares module

2020-02-11 05:51 UTC, supritaj commented
> Now since we have folders remove the corresponding models.py, views.py, tests.py files ... Add a views folder as well


> Now since we have folders remove the corresponding models.py, views.py, tests.py files ... Add a views folder as well

there is already a templates folder at root level, is views folder required then?

2020-02-12 06:31 UTC, closed without merging